### ISSUE TITLE
Update the link to use the new OTP url

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DN_ADMINUI#29]
We still use the link to the old page:

https://dappnode.github.io/DNP_VPN/DAppNode_OTP.html#otp=eyJzZ...

**Comment by dapplion** [comment]
The link is not generated in the UI, but in the VPN module. Changed the url in the dockerfile of the VPN
https://github.com/dappnode/DNP_VPN/commit/d4c141c4a7b34cc3ff63c9f65beca1c9ba594516
